language: python
python:
  - "2.7"
  - "3.2"
  - "3.3"
  # does not have headers provided, please ask https://launchpad.net/~pypy/+archive/ppa
  # maintainers to fix their pypy-dev package.
install:
  - pip install .
  - pip install -r requirements.txt
# command to run tests
script: python test_streams.py
